<?php

declare(strict_types=1);
get_header();
the_post();
$offices = get_posts(['post_type' => 'office', 'post_status' => 'publish', 'posts_per_page' => 4, 'orderby' => 'menu_order title', 'order' => 'ASC']);
?>
<main id="main-content"><header class="jp-page-hero jp-page-hero--archive"><div class="jp-container"><?php jp_breadcrumbs(); ?><p class="jp-eyebrow">Contact JusticePoint</p><h1>Choose the clearest way to reach us.</h1><p>Start with a secure consultation request, call a local office, or use the fictional profile email for non-confidential demonstration inquiries.</p><a class="jp-button jp-button--primary" href="<?php echo esc_url(home_url('/consultation/')); ?>">Request a consultation</a></div></header><section class="jp-container jp-section"><div class="jp-contact-grid"><article><p class="jp-eyebrow">General intake</p><h2>One point of contact.</h2><p><a class="jp-contact-link" href="tel:+12135550148">(213) 555-0148</a><br><a class="jp-contact-link" href="mailto:hello@justicepoint.example">hello@justicepoint.example</a></p><p>Monday–Friday, 8:30 a.m.–6:00 p.m.</p></article><article><p class="jp-eyebrow">Before you send</p><h2>Protect your information.</h2><p>Do not send confidential documents, Social Security numbers, medical records, or privileged communications through this demonstration.</p><a class="jp-text-link" href="<?php echo esc_url(home_url('/privacy/')); ?>">Read the privacy notice <span aria-hidden="true">→</span></a></article></div></section><section class="jp-surface jp-section"><div class="jp-container"><div class="jp-section-heading jp-section-heading--split"><div><p class="jp-eyebrow">Local offices</p><h2>Call the market nearest you.</h2></div><a class="jp-text-link" href="<?php echo esc_url(home_url('/office-directory/')); ?>">Open searchable directory <span aria-hidden="true">→</span></a></div><div class="jp-link-grid"><?php foreach ($offices as $office) : ?><a href="<?php echo esc_url(get_permalink($office)); ?>"><span><?php echo esc_html((string) jp_field('office_state', $office->ID)); ?></span><strong><?php echo esc_html($office->post_title); ?></strong><span><?php echo esc_html((string) jp_field('telephone', $office->ID)); ?></span></a><?php endforeach; ?></div></div></section></main>
<?php get_footer(); ?>

