<?php

declare(strict_types=1);
get_header();
the_post();
?>
<main id="main-content"><header class="jp-page-hero jp-page-hero--compact"><div class="jp-container"><?php jp_breadcrumbs(); ?><p class="jp-eyebrow">Demonstration policy</p><h1>Privacy</h1><p>This fictional policy documents how the portfolio demonstration is designed to handle intake and measurement data.</p></div></header><article class="jp-container jp-section jp-policy"><aside><nav aria-label="On this page"><a href="#data">Data collected</a><a href="#crm">CRM delivery</a><a href="#analytics">Analytics</a><a href="#retention">Retention</a><a href="#rights">Your choices</a></nav></aside><div class="jp-prose"><h2 id="data">Data the intake workflow collects</h2><p>The consultation form collects contact details, an inquiry summary, practice and office preferences, landing page, referrer, UTM parameters, and common advertising click IDs. The live demonstration is not intended for real legal requests or confidential information.</p><h2 id="crm">CRM delivery</h2><p>Server-side validation, nonce verification, a honeypot, and rate limiting run before delivery. The webhook endpoint and token are configured only through environment variables. Failed requests are retried, and logs contain request identifiers and status codes—not form contents or personally identifiable information.</p><h2 id="analytics">Analytics</h2><p>A GTM-style <code>dataLayer</code> event is emitted only after confirmed delivery. It records the form identifier and delivery mode; it never includes a name, email address, telephone number, message, or other PII.</p><h2 id="retention">Retention and security</h2><p>The mock adapter does not persist form contents. A production CRM would define access, encryption, retention, deletion, and incident-response requirements with the firm and its vendors.</p><h2 id="rights">Your choices</h2><p>Because this is a fictional local demonstration, do not submit personal information. In a production deployment, privacy requests would use a verified workflow appropriate to the applicable jurisdiction.</p><p><em>Last updated <?php echo esc_html(wp_date('F j, Y')); ?>.</em></p></div></article></main>
<?php get_footer(); ?>

