<?php

declare(strict_types=1);
get_header();
the_post();
$id = get_the_ID();
$practice_ids = (array) jp_field('served_practice_areas', $id, []);
$attorney_ids = get_posts(['post_type' => 'attorney', 'post_status' => 'publish', 'posts_per_page' => 20, 'fields' => 'ids']);
$attorney_ids = array_values(array_filter($attorney_ids, static fn ($attorney): bool => in_array($id, array_map('absint', (array) jp_field('offices', (int) $attorney, [])), true)));
$services = get_posts(['post_type' => 'service_area', 'post_status' => 'publish', 'posts_per_page' => 20, 'orderby' => 'title', 'order' => 'ASC', 'meta_key' => 'office', 'meta_value' => $id]);
$phone = (string) jp_field('telephone', $id);
?>
<main id="main-content"><article><header class="jp-page-hero"><div class="jp-container jp-page-hero__grid"><div><?php jp_breadcrumbs(); ?><p class="jp-eyebrow"><?php echo esc_html((string) jp_field('office_state', $id, 'California')); ?> office</p><h1><?php the_title(); ?></h1><p class="jp-page-hero__lede"><?php the_excerpt(); ?></p><div class="jp-page-hero__actions"><a class="jp-button jp-button--primary" href="<?php echo esc_url((string) jp_field('consultation_url', $id, home_url('/consultation/'))); ?>">Request a consultation</a><a class="jp-text-link" href="tel:<?php echo esc_attr((string) preg_replace('/[^+\d]/', '', $phone)); ?>"><?php echo esc_html($phone); ?></a></div></div><aside class="jp-hero-office"><p class="jp-eyebrow">Visit or call</p><address><?php echo esc_html((string) jp_field('address', $id)); ?><br><?php echo esc_html((string) jp_field('office_city', $id)); ?>, <?php echo esc_html((string) jp_field('office_state', $id)); ?> <?php echo esc_html((string) jp_field('zip_code', $id)); ?></address><p><?php echo nl2br(esc_html((string) jp_field('office_hours', $id))); ?></p><p><?php echo esc_html((string) jp_field('map_information', $id)); ?></p></aside></div></header>
<section class="jp-container jp-section jp-content-grid"><div class="jp-prose"><p class="jp-eyebrow">Local counsel, connected platform</p><h2>Employment guidance for <?php echo esc_html((string) jp_field('office_city', $id)); ?>.</h2><?php the_content(); ?></div><aside class="jp-aside-list"><p class="jp-eyebrow">Office contact</p><ul class="jp-icon-list"><li><span>Telephone</span><strong><a href="tel:<?php echo esc_attr((string) preg_replace('/[^+\d]/', '', $phone)); ?>"><?php echo esc_html($phone); ?></a></strong></li><li><span>Email</span><strong><a href="mailto:hello@justicepoint.example">hello@justicepoint.example</a></strong></li><li><span>Consultations</span><strong>By appointment</strong></li></ul></aside></section>
<?php if ($practice_ids) : ?><section class="jp-section jp-surface"><div class="jp-container"><div class="jp-section-heading jp-section-heading--split"><div><p class="jp-eyebrow">Capabilities</p><h2>Practice areas served here.</h2></div><p>Linked source records keep this list current without duplicating content in the office layout.</p></div><div class="jp-link-grid"><?php foreach ($practice_ids as $practice_id) : ?><a href="<?php echo esc_url(get_permalink((int) $practice_id)); ?>"><span>Employment law</span><strong><?php echo esc_html(get_the_title((int) $practice_id)); ?></strong><span aria-hidden="true">→</span></a><?php endforeach; ?></div></div></section><?php endif; ?>
<?php if ($services) : ?><section class="jp-container jp-section"><div class="jp-section-heading jp-section-heading--split"><div><p class="jp-eyebrow">Curated local pages</p><h2>Guidance for this market.</h2></div><p>Each page adds original local detail to a shared practice and office relationship.</p></div><div class="jp-featured-services"><?php foreach (array_slice($services, 0, 5) as $index => $service) : ?><article><span><?php echo esc_html(str_pad((string) ($index + 1), 2, '0', STR_PAD_LEFT)); ?></span><h3><a href="<?php echo esc_url(get_permalink($service)); ?>"><?php echo esc_html($service->post_title); ?></a></h3><p><?php echo esc_html(wp_trim_words(wp_strip_all_tags((string) jp_field('unique_local_intro', $service->ID)), 24)); ?></p><a class="jp-text-link" href="<?php echo esc_url(get_permalink($service)); ?>">Explore <span aria-hidden="true">→</span></a></article><?php endforeach; ?></div></section><?php endif; ?>
<div class="jp-container"><?php jp_render_attorneys($attorney_ids, 'People based in this market'); ?><section class="jp-section"><?php jp_context_cta($id); ?></section></div></article></main>
<?php get_footer(); ?>

