<?php

declare(strict_types=1);

namespace Liston\LegalWebOps\CLI;

use Liston\LegalWebOps\Migration\RedirectRepository;
use Liston\LegalWebOps\Migration\RedirectValidator;

final class RedirectsCommand
{
    /** Validate a redirect CSV before deployment. */
    public function validate(array $args, array $assoc_args): void
    {
        unset($assoc_args);
        $file = $this->file_arg($args);
        $result = (new RedirectValidator())->validate_file($file, true);
        $this->print_issues($result['issues']);
        if (! $result['valid']) {
            \WP_CLI::error(sprintf('Validation failed: %d row(s), %d issue(s).', count($result['rows']), count($result['issues'])));
        }
        \WP_CLI::success(sprintf('Validated %d redirect(s); no blocking errors.', count($result['rows'])));
    }

    /** Import a validated CSV. Use --dry-run to preview. */
    public function import(array $args, array $assoc_args): void
    {
        $file = $this->file_arg($args);
        $result = (new RedirectValidator())->validate_file($file, empty($assoc_args['skip-http-check']));
        $this->print_issues($result['issues']);
        if (! $result['valid']) {
            \WP_CLI::error('Import stopped because validation contains blocking errors.');
        }
        if (isset($assoc_args['dry-run'])) {
            \WP_CLI::success(sprintf('Dry run complete: %d redirect(s) are importable.', count($result['rows'])));
            return;
        }
        $repository = new RedirectRepository();
        $repository->install();
        $count = 0;
        foreach ($result['rows'] as $row) {
            $count += $repository->upsert($row['source'], $row['destination'], $row['status']) ? 1 : 0;
        }
        \WP_CLI::success(sprintf('Imported %d redirect(s).', $count));
    }

    /** Export Nginx rules from a validated CSV. */
    public function export_nginx(array $args, array $assoc_args): void
    {
        unset($assoc_args);
        $this->export_rules($this->file_arg($args), 'nginx');
    }

    /** Export Apache rules from a validated CSV. */
    public function export_apache(array $args, array $assoc_args): void
    {
        unset($assoc_args);
        $this->export_rules($this->file_arg($args), 'apache');
    }

    private function export_rules(string $file, string $server): void
    {
        $result = (new RedirectValidator())->validate_file($file, false);
        if (! $result['valid']) {
            $this->print_issues($result['issues']);
            \WP_CLI::error('Export stopped because validation contains blocking errors.');
        }
        $lines = ['# Generated by JusticePoint Legal WebOps; review in staging before deployment.'];
        foreach ($result['rows'] as $row) {
            $source = preg_quote(RedirectRepository::normalize_path($row['source']), '#');
            $destination = RedirectRepository::normalize_destination($row['destination']);
            if ($server === 'nginx') {
                $lines[] = sprintf('location = %s { return %d %s; }', RedirectRepository::normalize_path($row['source']), $row['status'], $destination);
            } else {
                $lines[] = sprintf('Redirect %d %s %s', $row['status'], RedirectRepository::normalize_path($row['source']), $destination);
            }
        }
        $extension = $server === 'nginx' ? '.nginx.conf' : '.apache.conf';
        $output = preg_replace('/\.csv$/i', '', $file) . $extension;
        $written = file_put_contents($output, implode(PHP_EOL, $lines) . PHP_EOL);
        if ($written === false) {
            \WP_CLI::error('Could not write ' . $output);
        }
        \WP_CLI::success(sprintf('Wrote %d one-hop %s rule(s) to %s.', count($result['rows']), $server, $output));
    }

    /** @param array<int,array{level:string,code:string,row:int,message:string}> $issues */
    private function print_issues(array $issues): void
    {
        foreach ($issues as $issue) {
            \WP_CLI::log(sprintf('[%s] row %d %s: %s', strtoupper($issue['level']), $issue['row'], $issue['code'], $issue['message']));
        }
    }

    /** @param array<int,string> $args */
    private function file_arg(array $args): string
    {
        if (empty($args[0])) {
            \WP_CLI::error('Provide a CSV path.');
        }
        $path = (string) $args[0];
        return str_starts_with($path, '/') ? $path : ABSPATH . ltrim($path, '/');
    }
}

