<?php

declare(strict_types=1);
$id = get_the_ID();
$practice_id = absint(jp_field('practice_area', $id));
$office_id = absint(jp_field('office', $id));
$city = (string) jp_field('office_city', $office_id, get_the_title($office_id));
$phone = (string) jp_field('telephone', $office_id, '(213) 555-0148');
$steps = jp_lines((string) jp_field('process_steps', $practice_id));
$nearby = jp_lines((string) jp_field('nearby_areas', $id));
$faqs = (array) jp_field('related_faqs', $id, jp_field('related_faqs', $practice_id, []));
$attorneys = (array) jp_field('assigned_attorneys', $id, jp_field('related_attorneys', $practice_id, []));
$include_context_cta = ! isset($jp_include_context_cta) || $jp_include_context_cta;
?>
<article class="jp-service-area">
    <header class="jp-page-hero jp-page-hero--service"><div class="jp-container jp-page-hero__grid"><div><?php jp_breadcrumbs(); ?><p class="jp-eyebrow"><?php echo esc_html($city); ?> employment law</p><h1><?php the_title(); ?></h1><div class="jp-page-hero__lede"><?php echo wp_kses_post(wpautop((string) jp_field('unique_local_intro', $id, get_the_excerpt()))); ?></div><div class="jp-page-hero__actions"><a class="jp-button jp-button--primary" href="<?php echo esc_url(home_url('/consultation/?practice_area=' . $practice_id . '&office=' . $office_id)); ?>">Request a consultation</a><a class="jp-text-link" href="tel:<?php echo esc_attr((string) preg_replace('/[^+\d]/', '', $phone)); ?>"><?php echo esc_html($phone); ?></a></div></div><aside class="jp-hero-office"><p class="jp-eyebrow">Your nearest JusticePoint office</p><h2><a href="<?php echo esc_url(get_permalink($office_id)); ?>"><?php echo esc_html(get_the_title($office_id)); ?></a></h2><address><?php echo esc_html((string) jp_field('address', $office_id)); ?><br><?php echo esc_html($city); ?>, <?php echo esc_html((string) jp_field('office_state', $office_id)); ?> <?php echo esc_html((string) jp_field('zip_code', $office_id)); ?></address><p><?php echo nl2br(esc_html((string) jp_field('office_hours', $office_id))); ?></p></aside></div></header>
    <div class="jp-service-meta"><div class="jp-container"><span>Practice</span><a href="<?php echo esc_url(get_permalink($practice_id)); ?>"><?php echo esc_html(get_the_title($practice_id)); ?></a><span>Market</span><a href="<?php echo esc_url(get_permalink($office_id)); ?>"><?php echo esc_html($city); ?></a><span>Campaign</span><strong><?php echo esc_html((string) jp_field('crm_campaign_id', $id, 'JP-LOCAL')); ?></strong></div></div>
    <section class="jp-container jp-section jp-content-grid"><div class="jp-prose"><p class="jp-eyebrow">Local perspective</p><h2>What to consider in <?php echo esc_html($city); ?>.</h2><?php echo wp_kses_post(wpautop((string) jp_field('local_legal_considerations', $id))); ?><h3>The broader practice context</h3><?php echo wp_kses_post(wpautop((string) jp_field('detailed_intro', $practice_id))); ?></div><aside class="jp-aside-list"><p class="jp-eyebrow">Office details</p><ul class="jp-icon-list"><li><span>Address</span><strong><?php echo esc_html((string) jp_field('address', $office_id)); ?></strong></li><li><span>Telephone</span><strong><a href="tel:<?php echo esc_attr((string) preg_replace('/[^+\d]/', '', $phone)); ?>"><?php echo esc_html($phone); ?></a></strong></li><li><span>Access</span><strong><?php echo esc_html((string) jp_field('map_information', $office_id)); ?></strong></li></ul></aside></section>
    <?php if ($steps) : ?><section class="jp-section jp-surface"><div class="jp-container"><div class="jp-section-heading jp-section-heading--split"><div><p class="jp-eyebrow">A measured process</p><h2>From first conversation to next decision.</h2></div><p>A repeatable layout draws the process from the linked practice area while preserving unique market content above.</p></div><ol class="jp-step-grid"><?php foreach ($steps as $index => $step) : ?><li><span><?php echo esc_html(str_pad((string) ($index + 1), 2, '0', STR_PAD_LEFT)); ?></span><h3><?php echo esc_html($step); ?></h3></li><?php endforeach; ?></ol></div></section><?php endif; ?>
    <div class="jp-container"><?php jp_render_attorneys($attorneys, 'Attorneys aligned to this service'); jp_render_faqs($faqs); ?><?php if ($nearby) : ?><section class="jp-section jp-nearby"><div><p class="jp-eyebrow">Nearby areas served</p><h2>Connected across the market.</h2></div><ul><?php foreach ($nearby as $area) : ?><li><?php echo esc_html($area); ?></li><?php endforeach; ?></ul></section><?php endif; ?><?php if ($include_context_cta) : ?><section class="jp-section"><?php jp_context_cta($office_id, $practice_id); ?></section><?php endif; ?></div>
</article>
